rm "/media/DISC02/OsMeusFilmes/Easy A (2010)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The First Grader (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Tiny Furniture (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The Eye of the Storm (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Like Crazy (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Bad Blood The Hatfields and McCoys (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The Ages of Love (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Foster (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Seven Days in Utopia (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The Source (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Teen Spirit (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/A Bird of the Air (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Thin Ice (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/For the Love of Money (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Come As You Are (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Delicacy (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The Snows of Kilimanjaro (2012)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/Romantics Anonymous (2011)/movie.nfo"
rm "/media/DISC02/OsMeusFilmes/The Best Exotic Marigold Hotel (2012)/movie.nfo"
rm "/media/DISC03/OsMeusFilmesHD/Splice (2011)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Night Drive (2010)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Love Likes Coincidences (2011)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Blood Done Sign My Name (2010)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Beginners (2011)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Abduction (2011)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Friends with Kids (2012)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Thin Ice (2011)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Lolita (1997)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/As Luck Would Have It (2012)/movie.nfo"
rm "/media/DISC05/OsMeusFilmes/Salmon Fishing in the Yemen (2012)/movie.nfo"
rm "/media/DISC05/OsMeusFilmesHD/Being Flynn (2012)/movie.nfo"
rm "/media/DISC05/OsMeusFilmesHD/Shame (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmes/Crimson Rivers 2 Angels of the Apocalypse (2004)/movie.nfo"
rm "/media/DISC06/OsMeusFilmes/The Lucky One (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/Treasure Island (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/The Three Stooges (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/New Year`s Eve (2011)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/Get the Gringo (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/God Bless America (2012)/movie.nfo"
rm "/media/DISC06/OsMeusFilmesHD/Piranha 3DD (2012)/movie.nfo"
